import prisma from "@/app/client";
import { NextRequest, NextResponse } from "next/server";

export async function GET(req: NextRequest) {
	const value = req.nextUrl.searchParams.get("search");
	const diseases = await prisma.diseases.findMany({
		where: {
			name: {
				contains: value || "",
				mode: "insensitive",
			},
		},
		take: 5,
	});
	return NextResponse.json(diseases);
}

export async function POST() {
	await prisma.diseases.createMany({
		data: [
			{ name: "Hypertension" },
			{ name: "Diabetes Mellitus" },
			{ name: "Asthma" },
			{ name: "Chronic Obstructive Pulmonary Disease (COPD)" },
			{ name: "Coronary Artery Disease" },
			{ name: "Stroke" },
			{ name: "Cancer" },
			{ name: "Alzheimer's Disease" },
			{ name: "Parkinson's Disease" },
			{ name: "Osteoporosis" },
			{ name: "Arthritis" },
			{ name: "Rheumatoid Arthritis" },
			{ name: "Osteoarthritis" },
			{ name: "Chronic Kidney Disease" },
			{ name: "Hepatitis B" },
			{ name: "Hepatitis C" },
			{ name: "HIV/AIDS" },
			{ name: "Tuberculosis" },
			{ name: "Pneumonia" },
			{ name: "Influenza" },
			{ name: "COVID-19" },
			{ name: "Migraine" },
			{ name: "Epilepsy" },
			{ name: "Multiple Sclerosis" },
			{ name: "Celiac Disease" },
			{ name: "Crohn's Disease" },
			{ name: "Ulcerative Colitis" },
			{ name: "Irritable Bowel Syndrome" },
			{ name: "Gastritis" },
			{ name: "Peptic Ulcer" },
			{ name: "Gastroesophageal Reflux Disease (GERD)" },
			{ name: "Chronic Fatigue Syndrome" },
			{ name: "Lupus" },
			{ name: "Psoriasis" },
			{ name: "Eczema" },
			{ name: "Dermatitis" },
			{ name: "Acne" },
			{ name: "Rosacea" },
			{ name: "Vitiligo" },
			{ name: "Sickle Cell Anemia" },
			{ name: "Hemophilia" },
			{ name: "Leukemia" },
			{ name: "Lymphoma" },
			{ name: "Anemia" },
			{ name: "Thalassemia" },
			{ name: "Gout" },
			{ name: "Fibromyalgia" },
			{ name: "Carpal Tunnel Syndrome" },
			{ name: "Tendonitis" },
			{ name: "Bursitis" },
			{ name: "Shingles" },
			{ name: "Chickenpox" },
			{ name: "Measles" },
			{ name: "Mumps" },
			{ name: "Rubella" },
			{ name: "Whooping Cough" },
			{ name: "Tetanus" },
			{ name: "Diphtheria" },
			{ name: "Pertussis" },
			{ name: "Polio" },
			{ name: "Malaria" },
			{ name: "Dengue" },
			{ name: "Zika Virus" },
			{ name: "Chikungunya" },
			{ name: "Yellow Fever" },
			{ name: "Rabies" },
			{ name: "Lyme Disease" },
			{ name: "Rocky Mountain Spotted Fever" },
			{ name: "Ebola" },
			{ name: "Marburg Virus" },
			{ name: "Hantavirus" },
			{ name: "Lassa Fever" },
			{ name: "Meningitis" },
			{ name: "Encephalitis" },
			{ name: "West Nile Virus" },
			{ name: "Zoster Virus" },
			{ name: "Hantavirus Pulmonary Syndrome" },
			{ name: "Middle East Respiratory Syndrome (MERS)" },
			{ name: "Severe Acute Respiratory Syndrome (SARS)" },
			{ name: "Avian Influenza" },
			{ name: "Swine Flu" },
			{ name: "Anthrax" },
			{ name: "Plague" },
			{ name: "Tularemia" },
			{ name: "Q Fever" },
			{ name: "Brucellosis" },
			{ name: "Botulism" },
			{ name: "Leptospirosis" },
			{ name: "Schistosomiasis" },
			{ name: "Trypanosomiasis" },
			{ name: "Leishmaniasis" },
			{ name: "Chagas Disease" },
			{ name: "Onchocerciasis" },
			{ name: "Filariasis" },
			{ name: "Dracunculiasis" },
			{ name: "Ascariasis" },
			{ name: "Hookworm Infection" },
			{ name: "Pinworm Infection" },
			{ name: "Toxocariasis" },
			{ name: "Strongyloidiasis" },
		],
	});
	return NextResponse.json("Succesful");
}
